<?php

namespace App\Services;

/**
 * Turns QA findings into a markdown prompt pack a developer can paste into
 * Cursor (or any coding agent) and act on immediately.
 *
 * QA prompts are ERROR-FIX oriented only: reproduce, expected vs actual,
 * evidence, done-when. Feature and UX suggestions belong on the smoke portal.
 */
class CursorPromptBuilder
{
    /**
     * @param array<string, mixed>       $payload session report JSON
     * @return string markdown
     */
    public function forSession(array $payload): string
    {
        $session = (array) ($payload['session'] ?? []);
        $result  = (array) ($payload['result'] ?? []);
        $run     = (array) ($payload['run'] ?? []);

        $failed = array_values(array_filter(
            (array) ($payload['validations'] ?? []),
            static fn ($v): bool => empty($v['passed'])
        ));
        $fileIo = array_values(array_filter(
            (array) ($payload['file_io_tests'] ?? []),
            static fn ($t): bool => in_array((string) ($t['compare_status'] ?? ''), ['fail', 'partial'], true)
        ));
        $steps = array_values(array_filter(
            (array) (($result['result_json']['failed_steps'] ?? [])),
            static fn ($s): bool => is_array($s)
        ));

        $lines = [
            '# QA fix prompts — ' . ($session['name'] ?? 'session'),
            '',
            '> Generated by the AICOUNTLY QA Portal. Every item below is a **defect or data'
            . ' mismatch observed by an automated run**, not a feature request.',
            '',
            $this->metaBlock($session, $run, $result),
            '',
        ];

        if ($failed === [] && $fileIo === [] && $steps === []) {
            $lines[] = '## Nothing to fix';
            $lines[] = '';
            $lines[] = 'This session recorded no failed validations, no failed steps, and no file I/O mismatches.';

            return implode("\n", $lines) . "\n";
        }

        $index = 1;
        foreach ($failed as $validation) {
            $lines[] = $this->validationPrompt($index++, $validation, $session, $result);
        }
        foreach ($fileIo as $test) {
            $lines[] = $this->fileIoPrompt($index++, $test, $session);
        }
        foreach ($steps as $step) {
            $lines[] = $this->stepPrompt($index++, $step, $session);
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param array<string, mixed> $payload final report JSON
     */
    public function forRun(array $payload): string
    {
        $run     = (array) ($payload['run'] ?? []);
        $totals  = (array) ($payload['totals'] ?? []);
        $qaRunId = (string) ($payload['qa_run_id'] ?? '');

        $lines = [
            '# QA fix prompts — run ' . $qaRunId,
            '',
            '> ' . (int) ($totals['total'] ?? 0) . ' session(s): '
            . (int) ($totals['passed'] ?? 0) . ' passed, '
            . (int) ($totals['failed'] ?? 0) . ' failed, '
            . (int) ($totals['skipped'] ?? 0) . ' skipped.',
            '',
            '- **Product:** ' . ($run['product_name'] ?? 'unknown'),
            '- **Environment:** ' . \Config\Environments::label((string) ($run['environment'] ?? '')),
            '- **Title:** ' . ($run['title'] ?? '(untitled run)'),
            '',
        ];

        $fileIoSummary = (array) ($payload['file_io_summary'] ?? []);
        if (($fileIoSummary['total'] ?? 0) > 0) {
            $lines[] = '- **File I/O:** ' . (int) ($fileIoSummary['by_status']['pass'] ?? 0) . ' passed / '
                . (int) $fileIoSummary['total'] . ' scenarios, '
                . (int) ($fileIoSummary['mismatched_cells'] ?? 0) . ' mismatched cell(s).';
            $lines[] = '';
        }

        $grouped = [];
        foreach ((array) ($payload['validations'] ?? []) as $validation) {
            if (! empty($validation['passed'])) {
                continue;
            }
            $code = (string) ($validation['rule_code'] ?? 'UNKNOWN');
            $grouped[$code][] = $validation;
        }

        if ($grouped === []) {
            $lines[] = '## Nothing to fix';
            $lines[] = '';
            $lines[] = 'No validation failed across this run.';

            return implode("\n", $lines) . "\n";
        }

        uasort($grouped, static fn (array $a, array $b): int => count($b) <=> count($a));

        $lines[] = '## Top errors by rule';
        $lines[] = '';
        $index = 1;
        foreach ($grouped as $code => $items) {
            $first = $items[0];
            $lines[] = '### ' . $index++ . '. ' . $code . ' — ' . count($items) . ' occurrence(s)';
            $lines[] = '';
            $lines[] = '**Expected:** ' . $this->orNone($first['expected'] ?? null);
            $lines[] = '**Actual:** ' . $this->orNone($first['actual'] ?? null);
            $lines[] = '**Severity:** ' . ($first['severity'] ?? 'medium');
            $lines[] = '';
            $lines[] = 'Reproduce the failure on ' . ($run['product_name'] ?? 'the product')
                . ', find the shared root cause behind all ' . count($items)
                . ' occurrence(s), implement the smallest safe fix, and add regression coverage.';
            $lines[] = '';
            $lines[] = '**Done when:** rule `' . $code . '` passes on a re-run of QA run ' . $qaRunId . '.';
            $lines[] = '';
        }

        return implode("\n", $lines) . "\n";
    }

    /**
     * @param array<string, mixed> $session
     * @param array<string, mixed> $run
     * @param array<string, mixed> $result
     */
    private function metaBlock(array $session, array $run, array $result): string
    {
        return implode("\n", array_filter([
            '- **QA run:** ' . ($session['qa_run_id'] ?? ''),
            '- **Product:** ' . ($run['product_name'] ?? ''),
            '- **Environment:** ' . \Config\Environments::label((string) ($run['environment'] ?? '')),
            '- **Module:** ' . trim(((string) ($session['module'] ?? '')) . ' / ' . ((string) ($session['sub_module'] ?? '')), ' /'),
            '- **Status:** ' . ($result['status'] ?? $session['status'] ?? 'unknown')
                . ' (severity ' . ($result['severity'] ?? 'low') . ')',
        ]));
    }

    /**
     * @param array<string, mixed> $validation
     * @param array<string, mixed> $session
     * @param array<string, mixed> $result
     */
    private function validationPrompt(int $index, array $validation, array $session, array $result): string
    {
        $code     = (string) ($validation['rule_code'] ?? 'UNKNOWN');
        $evidence = $this->evidenceList($result);

        return implode("\n", [
            '## ' . $index . '. Fix ' . $code,
            '',
            '**Severity:** ' . ($validation['severity'] ?? 'medium'),
            '',
            '**Reproduce**',
            '1. Sign in to ' . ($session['name'] ?? 'the target app') . ' as the QA user.',
            '2. Navigate to the ' . ($session['module'] ?? 'affected') . ' module'
                . (! empty($session['sub_module']) ? ' → ' . $session['sub_module'] : '') . '.',
            '3. Repeat the step that the QA session executed for rule `' . $code . '`.',
            '',
            '**Expected:** ' . $this->orNone($validation['expected'] ?? null),
            '',
            '**Actual:** ' . $this->orNone($validation['actual'] ?? null),
            '',
            ! empty($validation['diff']) ? "**Diff:**\n\n```\n" . $validation['diff'] . "\n```\n" : '',
            ! empty($validation['notes']) ? '**Notes:** ' . $validation['notes'] . "\n" : '',
            '**Evidence:** ' . $evidence,
            '',
            '**Done when:** the same QA session re-runs with `' . $code . '` passing and no new failure appears '
            . 'in the ' . ($session['module'] ?? 'affected') . ' module.',
            '',
        ]);
    }

    /**
     * @param array<string, mixed> $test
     * @param array<string, mixed> $session
     */
    private function fileIoPrompt(int $index, array $test, array $session): string
    {
        $key   = (string) ($test['scenario_key'] ?? 'file-io');
        $notes = trim((string) ($test['verification_notes'] ?? ''));

        $mismatchBlock = '';
        $mismatches = (array) ($test['mismatches_json'] ?? $test['mismatches'] ?? []);
        if ($mismatches !== []) {
            $rows = array_slice($mismatches, 0, 10);
            $mismatchBlock = "**Cell mismatches (first " . count($rows) . "):**\n\n```\n"
                . implode("\n", array_map(
                    static fn ($m): string => sprintf(
                        '%s.%s: expected "%s", got "%s"',
                        (string) ($m['key'] ?? '?'),
                        (string) ($m['column'] ?? '?'),
                        (string) ($m['expected'] ?? ''),
                        (string) ($m['actual'] ?? '')
                    ),
                    $rows
                ))
                . "\n```\n";
        }

        return implode("\n", array_filter([
            '## ' . $index . '. Fix file I/O scenario `' . $key . '`',
            '',
            '**Direction:** ' . ($test['direction'] ?? 'round_trip')
                . ' · **Status:** ' . ($test['compare_status'] ?? 'fail'),
            '',
            '**Reproduce**',
            '1. Open the ' . ($session['module'] ?? 'import/export') . ' screen used by scenario `' . $key . '`.',
            '2. Import the synthetic fixture `' . ($test['fixture_name'] ?? 'fixture') . '`.',
            '3. Export the same data back out and compare it with the fixture.',
            '',
            '**Expected:** the exported artifact keeps the fixture\'s MIME type ('
                . $this->orNone($test['source_mime'] ?? null) . '), structure, '
                . $this->orNone($test['rows_expected'] ?? null) . ' data row(s), and every key column value.',
            '',
            '**Actual:** MIME ' . $this->orNone($test['result_mime'] ?? null)
                . ', ' . $this->orNone($test['rows_found'] ?? null) . ' row(s), '
                . (int) ($test['mismatched_cells'] ?? 0) . ' mismatched cell(s)'
                . (empty($test['structure_ok']) ? ', structure check FAILED' : '') . '.',
            '',
            $notes !== '' ? '**Verification notes:** ' . $notes . "\n" : '',
            $mismatchBlock,
            '**Evidence:** artifacts are downloadable from the run\'s File I/O tab (keys: '
                . implode(', ', array_keys((array) ($test['artifact_paths_json'] ?? []))) . ').',
            '',
            '**Done when:** the round trip preserves row count, key column values, and numeric totals within tolerance.',
            '',
        ]));
    }

    /**
     * @param array<string, mixed> $step
     * @param array<string, mixed> $session
     */
    private function stepPrompt(int $index, array $step, array $session): string
    {
        return implode("\n", [
            '## ' . $index . '. Fix failed step `' . ($step['kind'] ?? 'step') . '`',
            '',
            '**Reproduce:** run the ' . ($session['name'] ?? 'QA') . ' workflow up to step #'
                . (int) ($step['index'] ?? 0) . '.',
            '',
            '**Expected:** the step completes without an error.',
            '',
            '**Actual:** ' . $this->orNone($step['error'] ?? null),
            '',
            '**Done when:** the workflow reaches the end of the session without this step erroring.',
            '',
        ]);
    }

    /** @param array<string, mixed> $result */
    private function evidenceList(array $result): string
    {
        $paths = array_slice((array) ($result['screenshot_paths'] ?? []), 0, 5);
        if ($paths === []) {
            return 'see the session report HTML (screenshots, console and network logs are embedded).';
        }

        return implode(', ', array_map(static fn ($p): string => '`' . basename((string) $p) . '`', $paths))
            . ' (embedded in the session report HTML).';
    }

    private function orNone(mixed $value): string
    {
        $text = trim((string) ($value ?? ''));

        return $text === '' ? '_(not recorded)_' : $text;
    }
}
