<?php

namespace App\Database\Seeds;

use CodeIgniter\CLI\CLI;
use CodeIgniter\Database\Seeder;

class ValidationRulesSeeder extends Seeder
{
    public function run(): void
    {
        $rules = [
            ['rule_code' => 'ACC_TB_BALANCED',            'rule_kind' => 'accounting', 'product_name' => null,    'title' => 'Trial Balance debit equals credit',                   'severity_on_fail' => 'critical', 'description' => 'TB debit total must equal credit total.',                                    'expression_json' => json_encode(['kind' => 'equality', 'left' => 'tb_debit_total', 'right' => 'tb_credit_total'])],
            ['rule_code' => 'ACC_LEDGER_RECONCILES',      'rule_kind' => 'accounting', 'product_name' => null,    'title' => 'Ledger opening + dr - cr equals closing',             'severity_on_fail' => 'critical', 'description' => 'Per ledger, opening + debit - credit must equal closing balance.',          'expression_json' => json_encode(['kind' => 'per_ledger_close'])],
            ['rule_code' => 'ACC_SALES_REGISTER_MATCH',   'rule_kind' => 'report',     'product_name' => 'books', 'title' => 'Sales register matches sales vouchers',                'severity_on_fail' => 'high',     'description' => 'Sum of sales register matches sum of sales voucher line totals.',           'expression_json' => json_encode(['kind' => 'register_vs_vouchers', 'register' => 'sales'])],
            ['rule_code' => 'ACC_PURCH_REGISTER_MATCH',   'rule_kind' => 'report',     'product_name' => 'books', 'title' => 'Purchase register matches purchase vouchers',          'severity_on_fail' => 'high',     'description' => 'Sum of purchase register matches sum of purchase voucher line totals.',     'expression_json' => json_encode(['kind' => 'register_vs_vouchers', 'register' => 'purchase'])],
            ['rule_code' => 'ACC_GST_OUTPUT_RATE_MATCH',  'rule_kind' => 'accounting', 'product_name' => 'books', 'title' => 'GST output equals taxable sales × rate',               'severity_on_fail' => 'critical', 'description' => 'CGST + SGST + IGST on output side must equal taxable sales × applicable rate.', 'expression_json' => json_encode(['kind' => 'gst_rate', 'side' => 'output'])],
            ['rule_code' => 'ACC_GST_INPUT_RATE_MATCH',   'rule_kind' => 'accounting', 'product_name' => 'books', 'title' => 'GST input equals taxable purchases × rate',            'severity_on_fail' => 'critical', 'description' => 'CGST + SGST + IGST on input side must equal taxable purchases × applicable rate.','expression_json' => json_encode(['kind' => 'gst_rate', 'side' => 'input'])],
            ['rule_code' => 'STK_QTY_MOVEMENT',           'rule_kind' => 'accounting', 'product_name' => 'books', 'title' => 'Stock quantity movement reconciles',                  'severity_on_fail' => 'high',     'description' => 'Opening + purchases - sales ± adjustments = closing per item.',             'expression_json' => json_encode(['kind' => 'stock_movement'])],
            ['rule_code' => 'STK_CLOSING_VALUE',          'rule_kind' => 'accounting', 'product_name' => 'books', 'title' => 'Closing stock value matches valuation',                'severity_on_fail' => 'high',     'description' => 'Closing stock value matches configured valuation rule.',                    'expression_json' => json_encode(['kind' => 'stock_value'])],
            ['rule_code' => 'PNL_GROSS_PROFIT',           'rule_kind' => 'report',     'product_name' => 'books', 'title' => 'P&L gross profit matches expected',                    'severity_on_fail' => 'high',     'description' => 'Gross profit on P&L equals expected_value gross_profit.',                   'expression_json' => json_encode(['kind' => 'metric', 'metric' => 'gross_profit'])],
            ['rule_code' => 'PNL_NET_PROFIT',             'rule_kind' => 'report',     'product_name' => 'books', 'title' => 'P&L net profit matches expected',                      'severity_on_fail' => 'high',     'description' => 'Net profit on P&L equals expected_value net_profit.',                       'expression_json' => json_encode(['kind' => 'metric', 'metric' => 'net_profit'])],
            ['rule_code' => 'BS_BALANCED',                'rule_kind' => 'report',     'product_name' => 'books', 'title' => 'Balance Sheet assets equal liabilities',               'severity_on_fail' => 'critical', 'description' => 'Total assets on BS must equal total liabilities + equity.',                 'expression_json' => json_encode(['kind' => 'equality', 'left' => 'bs_asset_total', 'right' => 'bs_liability_total'])],
            ['rule_code' => 'CASH_BANK_MATCH',            'rule_kind' => 'accounting', 'product_name' => 'books', 'title' => 'Cash/Bank balances reconcile with vouchers',            'severity_on_fail' => 'critical', 'description' => 'Closing cash/bank ledger balance = opening + receipts - payments ± contra.', 'expression_json' => json_encode(['kind' => 'cash_bank_reconcile'])],
            ['rule_code' => 'REPORTS_RECONCILE_VOUCHERS', 'rule_kind' => 'report',     'product_name' => null,    'title' => 'Reports reflect vouchers entered in QA run',           'severity_on_fail' => 'high',     'description' => 'Reports must reflect vouchers tagged with current qa_run_id.',              'expression_json' => json_encode(['kind' => 'qa_run_visibility'])],
            ['rule_code' => 'REG_VOUCHER_COUNT',          'rule_kind' => 'report',     'product_name' => null,    'title' => 'Register voucher count matches expected',              'severity_on_fail' => 'medium',   'description' => 'Voucher count shown in registers equals expected count.',                   'expression_json' => json_encode(['kind' => 'voucher_count'])],
            ['rule_code' => 'DATE_FILTER_WORKS',          'rule_kind' => 'workflow',   'product_name' => null,    'title' => 'Date filters return expected rows',                    'severity_on_fail' => 'medium',   'description' => 'Applying date filters changes the result set as expected.',                 'expression_json' => json_encode(['kind' => 'date_filter'])],
            ['rule_code' => 'CTX_PERSISTENCE',            'rule_kind' => 'workflow',   'product_name' => null,    'title' => 'Company/branch/FY context persists',                   'severity_on_fail' => 'high',     'description' => 'Selected company/branch/FY remains across screens.',                        'expression_json' => json_encode(['kind' => 'context_persists'])],

            ['rule_code' => 'UI_REQUIRED_FIELDS',         'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Required fields show validation',                      'severity_on_fail' => 'medium',   'description' => 'Submitting empty required fields shows visible validation errors.',         'expression_json' => json_encode(['kind' => 'required_validation'])],
            ['rule_code' => 'UI_SAVE_WORKS',              'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Save buttons persist data',                            'severity_on_fail' => 'critical', 'description' => 'Save button persists data and shows success feedback.',                     'expression_json' => json_encode(['kind' => 'save_button'])],
            ['rule_code' => 'UI_CANCEL_WORKS',            'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Cancel/back buttons work',                             'severity_on_fail' => 'medium',   'description' => 'Cancel/back returns to the previous screen without saving.',                'expression_json' => json_encode(['kind' => 'cancel_button'])],
            ['rule_code' => 'UI_SEARCH_WORKS',            'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Search/filter return matching rows',                   'severity_on_fail' => 'medium',   'description' => 'Search and filter widgets narrow the result set as expected.',              'expression_json' => json_encode(['kind' => 'search_filter'])],
            ['rule_code' => 'UI_KEYBOARD_FLOW',           'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Keyboard tab/enter flow works',                        'severity_on_fail' => 'medium',   'description' => 'Tab and Enter navigate fields in the expected order.',                       'expression_json' => json_encode(['kind' => 'keyboard_flow'])],
            ['rule_code' => 'UI_NO_BLANK_PAGE',           'rule_kind' => 'ui',         'product_name' => null,    'title' => 'No page renders blank',                                'severity_on_fail' => 'critical', 'description' => 'Every navigated page returns visible content within timeout.',               'expression_json' => json_encode(['kind' => 'no_blank'])],
            ['rule_code' => 'UI_NO_CRITICAL_CONSOLE',     'rule_kind' => 'ui',         'product_name' => null,    'title' => 'No critical console errors',                           'severity_on_fail' => 'high',     'description' => 'No console.error / uncaught exception during the session.',                  'expression_json' => json_encode(['kind' => 'console_errors'])],
            ['rule_code' => 'UI_NO_UNHANDLED_API',        'rule_kind' => 'ui',         'product_name' => null,    'title' => 'No failed API call without UI handling',               'severity_on_fail' => 'high',     'description' => 'No 4xx/5xx response without a user-visible message.',                        'expression_json' => json_encode(['kind' => 'network_errors'])],
            ['rule_code' => 'UI_OLD_THEME_DETECTED',      'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Old/legacy theme pages detected',                      'severity_on_fail' => 'low',      'description' => 'Pages still using legacy theme are flagged.',                                'expression_json' => json_encode(['kind' => 'legacy_theme'])],
            ['rule_code' => 'UI_GREEN_WHITE_THEME',       'rule_kind' => 'ui',         'product_name' => null,    'title' => 'Green-white theme consistency',                        'severity_on_fail' => 'low',      'description' => 'Primary brand colour and white background remain consistent.',               'expression_json' => json_encode(['kind' => 'theme_consistency'])],
        ];

        $now = date('Y-m-d H:i:s');
        foreach ($rules as &$r) {
            $r['is_active']  = true;
            $r['created_at'] = $now;
            $r['updated_at'] = $now;
        }

        $this->db->table('qa_validation_rules')->ignore(true)->insertBatch($rules);
        CLI::write('Seeded ' . count($rules) . ' validation rules.', 'green');
    }
}
